openapi: 3.0.0
servers:
- url: http://helloworld
info:
  description: Sample Hello World API
  version: 2.0.0
  title: Hello-API
  termsOfService: http://swagger.io/terms/
tags:
- name: hello
x-wso2-basePath: /hello/{version}
x-wso2-production-endpoints:
  urls:
  - http://helloworld
x-wso2-sandbox-endpoints:
  urls:
  - http://helloworld
paths:
  /*:
    get:
      responses:
        "200":
          description: OK
      x-auth-type: Application & Application User
      x-throttling-tier: null
      x-wso2-application-security:
        security-types:
        - oauth2
        optional: false