openapi: 3.0.0
servers:
- url: https://run.mocky.io/v3/6a1c7d31-fba8-4ad0-a0ab-05380c58e23a
info:
  description: Sample Hello World API
  version: 1.0.0
  title: Hello-API
  termsOfService: http://swagger.io/terms/
tags:
- name: hello
x-wso2-basePath: /hello/{version}
x-wso2-production-endpoints:
  urls:
  - https://run.mocky.io/v3/6a1c7d31-fba8-4ad0-a0ab-05380c58e23a
x-wso2-sandbox-endpoints:
  urls:
  - https://run.mocky.io/v3/6a1c7d31-fba8-4ad0-a0ab-05380c58e23a
paths:
  /*:
    get:
      responses:
        "200":
          description: OK
      x-auth-type: Application & Application User
      x-throttling-tier: null
      x-wso2-application-security:
        security-types:
        - oauth2
        optional: false