openapi: 3.0.1
info:
  title: HeathCareAPI
  version: 1.0.0
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /:
    post:
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - oauth2
        optional: false
components:
  schemas:
    Request:
      required:
       - appointment_date
       - cardNo
       - dob
       - doctor
       - hospital
       - name
       - phone
       - ssn
      properties:
        name:
          type: string
        dob:
          type: string
        ssn:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string
        doctor:
          type: string
        hospital:
          type: string
        cardNo:
          type: string
        appointment_date:
          type: string
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - testKey
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://localhost:8290/health/surgery/reserve
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://localhost:8290/health/surgery/reserve
  type: http
x-wso2-basePath: /reserve/1.0.0
x-wso2-transports:
 - http
 - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
